package paneles;

import java.awt.*;
import javax.swing.*;

public class OvalPanel extends JPanel {

    @Override
    public void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        Boolean salir = false;
        int tamañoPantallaX=this.getWidth();
        int width = 33;
        int height = 33;
        int posicionx = 0;
        int posiciony = 0;
        System.out.println("hola"+tamañoPantallaX);
//        for (int i = 0; salir == true; i++) {
//            ;
//            if (posicionx <= this.getWidth()) {
//                System.out.println(posicionx);
//                posicionx+=33;
//                g.drawRect(posicionx, posiciony, width, height);
//                g.setColor(Color.red);
//            }else{
//                salir=false;
//            }
//        }
g.drawRect(posicionx, posiciony, width, height);
                g.setColor(Color.red);
    }
    
// public void paintComponent(Graphics g) {
// int width = getWidth();
// int height = getHeight();
// g.setColor(Color.red);
// g.drawRect(0, 0, width, height);
// }
    public static void main(String args[]) {
        Runnable runner = () -> {
//            JFrame frame = new JFrame("Oval Sample");
//            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//            frame.setLayout(new GridLayout(2, 2));
            
//            for (int i = 0; i < 4; i++) {
//                
//// frame.add(panel);
//            }
//            frame.setSize(300, 200);
//            frame.setVisible(true);
        };
        EventQueue.invokeLater(runner);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
