package paneles;

import java.awt.*;
import javax.swing.*;
public class OvalPanel extends JPanel {
 Color color;
 public OvalPanel() {
 this(Color.black);
 }
 public OvalPanel(Color color) {
 this.color = color;
 }
 public void paintComponent(Graphics g) {
 int width = getWidth();
 int height = getHeight();
 g.setColor(color);
 g.drawOval(0, 0, width, height);
 }
 public static void main(String args[]) {
 Runnable runner = new Runnable() {
 public void run() {
 JFrame frame = new JFrame("Oval Sample");
 frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
 frame.setLayout(new GridLayout(2, 2));
 Color colors[] = {Color.RED, Color.BLUE, Color.GREEN, Color.YELLOW};
 for (int i=0; i<4; i++) {
 OvalPanel panel = new OvalPanel(colors[i]);
 frame.add(panel);
 }
 frame.setSize(300, 200);
 frame.setVisible(true);
 }
 };
 EventQueue.invokeLater(runner);
 }

 

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
